export const assessmentItems = {
  en: [
    'Developmental Assessments',
    'Psychological Assessments',
    'Cognitive Assessments',
    'Intelligence (IQ) Assessments',
    'Behavioral Assessments',
    'Adaptive Functioning Assessments',
    'School Readiness Evaluations',
    'Executive Function Assessments',
    'Attention, Memory, and Learning Assessments',
    'Autism and Neurodevelopmental Screening',
  ],
  ar: [
    'التقييمات النمائية',
    'التقييمات النفسية',
    'التقييمات المعرفية',
    'تقييم الذكاء (IQ)',
    'التقييمات السلوكية',
    'تقييم المهارات التكيفية',
    'تقييم الاستعداد المدرسي',
    'تقييم الوظائف التنفيذية',
    'تقييم الانتباه والذاكرة ومهارات التعلّم',
    'فحوص اضطراب طيف التوحّد والاضطرابات النمائية العصبية',
  ],
};

export const interventionItems = {
  en: [
    'Applied Behavior Analysis (ABA)',
    'Behavioral Intervention',
    'Cognitive Training',
    'Executive Function Training',
    'Attention and Memory Training',
    'Social Skills Development',
    'Emotional Regulation Skills',
    'Communication and Functional Skills Support',
    'Daily Living and Independence Skills',
    'School Readiness Programs',
    'Learning Support',
    'Skill Development Programs',
    'Individual Development Plans',
  ],
  ar: [
    'تحليل السلوك التطبيقي (ABA)',
    'التدخل السلوكي',
    'التدريب المعرفي',
    'تدريب الوظائف التنفيذية',
    'تدريب الانتباه والذاكرة',
    'تنمية المهارات الاجتماعية',
    'تنمية مهارات التنظيم الانفعالي',
    'دعم مهارات التواصل والمهارات الوظيفية',
    'مهارات الحياة اليومية والاستقلالية',
    'برامج الاستعداد المدرسي',
    'الدعم الأكاديمي والتعلّمي',
    'برامج تنمية المهارات',
    'الخطط التنموية الفردية',
  ],
};

export const partnershipItems = {
  en: [
    'Parent Guidance',
    'Parent Coaching',
    'Home Program Development',
    'Progress Reviews',
    'Practical Strategies for Daily Life',
    'Collaborative Goal Setting',
  ],
  ar: [
    'إرشاد الوالدين',
    'تدريب الوالدين',
    'تطوير البرامج المنزلية',
    'متابعة التقدم وقياس أثره',
    'استراتيجيات عملية للحياة اليومية',
    'تحديد الأهداف بالتشارك مع الأسرة',
  ],
};
